name: Setup Env
on:
  workflow_dispatch: 
  push:
    paths:
      - 'policies/**'
      - 'tf/**'
jobs:
  test-sentinel-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Sentinel
        working-directory: ./policies
        run: |
          curl https://releases.hashicorp.com/sentinel/0.26.0/sentinel_0.26.0_linux_amd64.zip --output sentinel.zip
          unzip sentinel.zip
      - name: Sentinel Version
        working-directory: ./policies
        run: ./sentinel version
      - name: Sentinel Format
        working-directory: ./policies
        run: ./sentinel fmt */*.sentinel
      - name: Run Sentinel Policy Tests
        working-directory: ./policies
        run: ./sentinel test */
  create-policy-set:
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./tf/tfc-config
    needs: test-sentinel-policy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://hcp-vault-demo.vault.5bbc50e3-a284-4743-877e-ffd388d684f2.aws.hashicorp.cloud:8200
          namespace: admin/demo
          role: demo
          method: jwt
          secrets: |
            terraform/creds/demo token | TF_VAR_token ;
            secret/data/demo/vcs oauth_key | TF_VAR_vcs_oauth_key ;
      - name: Setup TF
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ env.TF_VAR_token }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init Prod
        env:
          TF_VAR_branch: main
          TF_WORKSPACE: tfc-config-prod
        id: init-prd
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan Prod
        env:
          TF_VAR_branch: main
          # TF_WORKSPACE: tfc-config-prod
        id: plan-prd
        run: terraform plan -no-color

      - name: Terraform apply Prod
        env:
          TF_VAR_branch: main
          # TF_WORKSPACE: tfc-config-prod
        id: apply-prd
        run: terraform apply -auto-approve
